name: GameJobs Prod Build Process
on:
  push:
    branches: [ master ]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 7
          format: 'YYYYMMDDHHmmss'
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: asia.gcr.io
          project_id: flextech-production
          image_name: ft.skc.game-jobs
          image_tag: ${{ steps.time.outputs.time }},latest
          dockerfile: ./GameJobs/Dockerfile
